In [17]:
 import os
from skimage import color, io, measure, img_as_ubyte
from skimage.measure import profile_line
from skimage.transform import rescale, resize

import matplotlib.pyplot as plt
import numpy as np
%matplotlib qt


import pydicom as dicom

Exercise 1

In [2]:
import numpy as np
in_dir = 'data/'
txt_name = 'irisdata.txt'
iris_data = np.loadtxt(in_dir + txt_name, comments="%")
# x is a matrix with 50 rows and 4 columns
x = iris_data[0:50, 0:4]

Exercise 1b

In [3]:
n_feat = x.shape[1]
n_obs = x.shape[0]
print(f"Number of features: {n_feat} and number of observations: {n_obs}")

Number of features: 4 and number of observations: 50


Exercise 2

In [5]:
sep_l = x[:, 0]
sep_w = x[:, 1]
pet_l = x[:, 2]
pet_w = x[:, 3]

Exercise 2b

In [6]:
# Use ddof = 1 to make an unbiased estimate
var_sep_l = sep_l.var(ddof=1)
var_sep_w=sep_w.var(ddof=1)
var_pet_l = pet_l.var(ddof=1)
var_pet_w = pet_w.var(ddof=1)


Exercise 3

In [13]:
cov_l = sep_l.dot(pet_l)/(n_obs - 1)
cov_w = sep_l.dot(sep_w)/(n_obs -1)

# Print results
print(f"Sepal length, petal length covariance: {cov_l:.2f}")
print(f"Sepal length, sepal width covariance: {cov_w:.2f}")

Sepal length, petal length covariance: 7.48
Sepal length, sepal width covariance: 17.61


Exercise 4

In [19]:
import seaborn as sns
import pandas as pd

plt.figure() # Added this to make sure that the figure appear
# Transform the data into a Pandas dataframe
d = pd.DataFrame(x, columns=["Sepal length", "Sepal width",
							 "Petal length", "Petal width"])
sns.pairplot(d)
plt.show()

Execise 5

In [20]:
mn = np.mean(x, axis=0)
data = x - mn

Exercise 5b

In [21]:
N = data.shape[0]  # number of samples
C_manual = np.matmul(data.T, data) / (N - 1)
C_numpy = np.cov(x.T)  # Use x.T because np.cov expects features as rows by default
print("Manual covariance matrix:\n", C_manual)
print("\nNumPy covariance matrix:\n", C_numpy)

# Check difference
print("\nDifference:\n", C_manual - C_numpy)

# Or use np.allclose to verify numerical equality
print("\nAre they approximately equal?", np.allclose(C_manual, C_numpy))


Manual covariance matrix:
 [[0.12424898 0.09921633 0.0163551  0.01033061]
 [0.09921633 0.1436898  0.01169796 0.00929796]
 [0.0163551  0.01169796 0.03015918 0.00606939]
 [0.01033061 0.00929796 0.00606939 0.01110612]]

NumPy covariance matrix:
 [[0.12424898 0.09921633 0.0163551  0.01033061]
 [0.09921633 0.1436898  0.01169796 0.00929796]
 [0.0163551  0.01169796 0.03015918 0.00606939]
 [0.01033061 0.00929796 0.00606939 0.01110612]]

Difference:
 [[1.38777878e-17 1.38777878e-17 0.00000000e+00 0.00000000e+00]
 [1.38777878e-17 2.77555756e-17 1.73472348e-18 1.73472348e-18]
 [0.00000000e+00 1.73472348e-18 3.46944695e-18 8.67361738e-19]
 [0.00000000e+00 1.73472348e-18 8.67361738e-19 0.00000000e+00]]

Are they approximately equal? True


Exercise 6

In [24]:
values, vectors = np.linalg.eig(C_manual) # Here c_x is your covariance matrix.

Exercise 7

In [27]:
v_norm = values / values.sum() * 100
plt.plot(v_norm)
plt.xlabel("Principal component")
plt.ylabel("Percent explained variance")
plt.ylim([0, 100])

plt.show()

Exercise 8

In [28]:
pc_proj = vectors.T.dot(data.T)

plt.figure() # Added this to make sure that the figure appear
# Transform the data into a Pandas dataframe
d = pd.DataFrame(pc_proj.T, columns=['PC1', 'PC2', 'PC3', 'PC4'])

p = sns.pairplot(d)
p.set(xlim=(-1,1), ylim = (-1,1))
plt.show()

Exercise 9

In [30]:
from sklearn import decomposition

pca = decomposition.PCA()
pca.fit(x)
values_pca = pca.explained_variance_
exp_var_ratio = pca.explained_variance_ratio_
vectors_pca = pca.components_

data_transform = pca.transform(x)

plt.figure()

d = pd.DataFrame(data_transform, columns=['PC1', 'PC2', 'PC3', 'PC4'])

p = sns.pairplot(d)
p.set(xlim=(-1,1), ylim = (-1,1))
plt.show()