In [1]:
from skimage import io
from skimage.color import rgb2gray
import matplotlib.pyplot as plt
import numpy as np

%matplotlib qt

In [2]:
from scipy.ndimage import correlate
input_img = np.arange(25).reshape(5, 5)
print(input_img)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [3]:
weights = [[0, 1, 0],
		   [1, 2, 1],
		   [0, 1, 0]]

res_img = correlate(input_img, weights)

Exercise 1

In [5]:
print(res_img)
print(f"Value (3, 3): \n {res_img[3, 3]}")

[[  6  11  17  23  28]
 [ 31  36  42  48  53]
 [ 61  66  72  78  83]
 [ 91  96 102 108 113]
 [116 121 127 133 138]]
Value (3, 3): 
 108


Exercise 2

In [9]:
img_reflect = correlate(input_img,weights, mode="reflect")
img_constant = correlate(input_img,weights,  mode="constant", cval=10)

# Show all images
fig, ax = plt.subplots(1, 3, figsize=(15, 5))

ax[0].imshow(input_img, cmap="gray")
ax[0].set_title("Original Image")
ax[0].axis("off")

ax[1].imshow(img_reflect, cmap="gray")
ax[1].set_title("Filtered (reflect padding)")
ax[1].axis("off")

ax[2].imshow(img_constant, cmap="gray")
ax[2].set_title("Filtered (constant padding, cval=10)")
ax[2].axis("off")

plt.tight_layout()
plt.show()

In [10]:
print(img_reflect)

[[  6  11  17  23  28]
 [ 31  36  42  48  53]
 [ 61  66  72  78  83]
 [ 91  96 102 108 113]
 [116 121 127 133 138]]


In [11]:
print(img_constant)

[[ 26  20  25  30  40]
 [ 36  36  42  48  54]
 [ 61  66  72  78  79]
 [ 86  96 102 108 104]
 [ 96 110 115 120 110]]


Exercise 3

In [13]:
img = io.imread("data/Gaussian.png")

# Convert to grayscale if it's RGB
if img.ndim == 3:
    img = rgb2gray(img)

# Try different filter sizes
filter_sizes = [5, 10, 20, 40]

# Plot original
plt.figure(figsize=(5, 5))
plt.imshow(img, cmap='gray')
plt.title("Original Image (with Gaussian Noise)")
plt.axis('off')
plt.show()


In [16]:
for size in filter_sizes:
    weights = np.ones((size, size)) / (size * size)
    filtered_img = correlate(img, weights, mode='reflect')

    plt.figure(figsize=(5, 5))
    plt.imshow(filtered_img, cmap='gray')
    plt.title(f"Mean Filter (size = {size}x{size})")
    plt.axis('off')
    plt.show()


Exercise 4

In [21]:
from skimage.filters import median
for size in [5, 10, 20]:
    footprint = np.ones((size, size))
    filtered = median(img, footprint=footprint)

    plt.figure(figsize=(5, 5))
    plt.imshow(filtered, cmap='gray')
    plt.title(f"Median Filter on Gaussian.png (size = {size}x{size})")
    plt.axis("off")
    plt.show()

Exercise 5

In [23]:
img_sp = io.imread("data/SaltPepper.png")
if img_sp.ndim == 3:
    img_sp = rgb2gray(img_sp)

# Try different filter sizes
filter_sizes = [3, 5, 11, 21]

for size in filter_sizes:
    # Mean filter
    mean_weights = np.ones((size, size)) / (size * size)
    mean_result = correlate(img_sp, mean_weights, mode='reflect')

    # Median filter
    median_result = median(img_sp, footprint=np.ones((size, size)))

    # Display results
    fig, axs = plt.subplots(1, 3, figsize=(15, 5))
    axs[0].imshow(img_sp, cmap='gray')
    axs[0].set_title("Original (Salt-and-Pepper)")
    axs[0].axis("off")

    axs[1].imshow(mean_result, cmap='gray')
    axs[1].set_title(f"Mean Filter ({size}x{size})")
    axs[1].axis("off")

    axs[2].imshow(median_result, cmap='gray')
    axs[2].set_title(f"Median Filter ({size}x{size})")
    axs[2].axis("off")

    plt.tight_layout()
    plt.show()

Exercise 6

In [25]:
from skimage.filters import gaussian
sigmas = [0.5, 1, 2, 4]

# Show original image
plt.figure(figsize=(5, 5))
plt.imshow(img, cmap='gray')
plt.title("Original Image (with Gaussian noise)")
plt.axis("off")
plt.show()

# Apply and display Gaussian filter results
for sigma in sigmas:
    gauss_img = gaussian(img, sigma=sigma)

    plt.figure(figsize=(5, 5))
    plt.imshow(gauss_img, cmap='gray')
    plt.title(f"Gaussian Filter (σ = {sigma})")
    plt.axis("off")
    plt.show()

Exercise 7

In [26]:
from skimage import io, color
from skimage.filters import gaussian, median
import matplotlib.pyplot as plt
import numpy as np

# Load the image (your own or car.png)
img = io.imread("data/car.png")

# Convert to grayscale
if img.ndim == 3:
    img_gray = color.rgb2gray(img)
else:
    img_gray = img

# Apply large Gaussian filter
gaussian_filtered = gaussian(img_gray, sigma=10)

# Apply large Median filter
footprint = np.ones((21, 21))  # 21x21 median filter
median_filtered = median(img_gray, footprint=footprint)

# Show results
fig, axs = plt.subplots(1, 3, figsize=(18, 6))

axs[0].imshow(img_gray, cmap='gray')
axs[0].set_title("Original Grayscale Image")
axs[0].axis('off')

axs[1].imshow(gaussian_filtered, cmap='gray')
axs[1].set_title("Gaussian Filtered (σ = 10)")
axs[1].axis('off')

axs[2].imshow(median_filtered, cmap='gray')
axs[2].set_title("Median Filtered (21×21)")
axs[2].axis('off')

plt.tight_layout()
plt.show()


Exercise 8

In [ ]:
from skimage.filters import prewitt_h
from skimage.filters import prewitt_v
from skimage.filters import prewitt

In [27]:
from skimage import io, color
from skimage.filters import prewitt_h, prewitt_v
import matplotlib.pyplot as plt

# Load and convert to grayscale
img = io.imread("data/donald_1.png")
if img.ndim == 3:
    img_gray = color.rgb2gray(img)

# Apply Prewitt filters
edges_h = prewitt_h(img_gray)
edges_v = prewitt_v(img_gray)

# Show the results without converting to uint8
fig, ax = plt.subplots(1, 3, figsize=(15, 5))

ax[0].imshow(img_gray, cmap='gray')
ax[0].set_title("Original Image")
ax[0].axis("off")

ax[1].imshow(edges_h, cmap='gray', vmin=-1, vmax=1)
ax[1].set_title("Prewitt Horizontal (prewitt_h)")
ax[1].axis("off")

ax[2].imshow(edges_v, cmap='gray', vmin=-1, vmax=1)
ax[2].set_title("Prewitt Vertical (prewitt_v)")
ax[2].axis("off")

plt.tight_layout()
plt.show()


Exercise 9

In [28]:
from skimage import io, color, filters
import numpy as np
import matplotlib.pyplot as plt

# Load and convert to grayscale
img = io.imread("data/donald_1.png")
if img.ndim == 3:
    img = color.rgb2gray(img)

# Apply Prewitt filters
gx = filters.prewitt_h(img)
gy = filters.prewitt_v(img)

# Combine gradients to get edge magnitude
magnitude = np.sqrt(gx**2 + gy**2)

# Show results
fig, ax = plt.subplots(1, 2, figsize=(12, 5))
ax[0].imshow(img, cmap='gray')
ax[0].set_title("Original Image")
ax[0].axis("off")

ax[1].imshow(magnitude, cmap='gray')
ax[1].set_title("Prewitt Edge Magnitude")
ax[1].axis("off")

plt.tight_layout()
plt.show()


Exercise 10

In [29]:
from skimage import io, color, filters
from skimage.filters import median, gaussian, threshold_otsu, prewitt_h, prewitt_v
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Load CT image
img = io.imread("data/ElbowCTSlice.png")
if img.ndim == 3:
    img = color.rgb2gray(img)

# Step 2: Denoising — Try Gaussian or Median here
# Try changing sigma or footprint size to experiment
sigma = 2
filtered_img = gaussian(img, sigma=sigma)
# OR try:
# from skimage.morphology import square
# filtered_img = median(img, footprint=square(5))

# Step 3: Compute gradient magnitude using Prewitt
gx = prewitt_h(filtered_img)
gy = prewitt_v(filtered_img)
edge_img = np.sqrt(gx**2 + gy**2)

# Step 4: Visualize gradient image with scaling
min_val = edge_img.min()
max_val = edge_img.max()
plt.figure(figsize=(6, 5))
io.imshow(edge_img, vmin=min_val, vmax=max_val, cmap="terrain")
plt.title("Prewitt Gradient Magnitude")
plt.axis("off")
plt.show()

# Step 5: Threshold using Otsu's method
T = threshold_otsu(edge_img)
binary_edges = edge_img > T

# Step 6: Show final binary edge map
plt.figure(figsize=(6, 5))
io.imshow((binary_edges), cmap="gray")
plt.title(f"Binary Edges (Otsu T = {T:.4f})")
plt.axis("off")
plt.show()


Exercise 11

In [30]:
!python Ex4_video_filtering.py 1 0 0

Starting image capture
Opening connection to camera
Starting camera loop
Can't receive frame. Exiting ...
Stopping image loop


Exercise 12

In [ ]:
!python Ex4_video_filtering.py 1 1 1