In [10]:
import numpy as np
from skimage import color, io
from skimage.color import rgb2gray
from skimage.filters import threshold_otsu
from skimage.morphology import erosion, dilation, opening, closing
from skimage.morphology import disk
import matplotlib.pyplot as plt

%matplotlib qt

Exercise 1

In [11]:
# Provided comparison function
def plot_comparison(original, filtered, filter_name):
    fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(8, 4), sharex=True, sharey=True)
    ax1.imshow(original, cmap=plt.cm.gray)
    ax1.set_title('Original')
    ax1.axis('off')
    ax2.imshow(filtered, cmap=plt.cm.gray)
    ax2.set_title(filter_name)
    ax2.axis('off')
    io.show()

# Step 1: Read the image
im_org = io.imread("data/lego_5.png")

# Step 2: Convert to grayscale
im_gray = color.rgb2gray(im_org)

# Step 3: Compute Otsu's threshold
T = threshold_otsu(im_gray)

# Step 4: Generate binary image
bin_img = im_gray > T

# Step 5: Show original grayscale and binary image
plot_comparison(im_gray, bin_img, "Binary image")

Exercise 2

In [12]:
from skimage.morphology import erosion, disk

# Create a disk-shaped footprint of radius 2
footprint = disk(2)

# Check the shape of the structuring element
print("Footprint:\n", footprint)

# Apply erosion to the binary LEGO image
eroded = erosion(bin_img, footprint)

# Visualize the result
plot_comparison(bin_img, eroded, 'Erosion (radius = 2)')


Footprint:
 [[0 0 1 0 0]
 [0 1 1 1 0]
 [1 1 1 1 1]
 [0 1 1 1 0]
 [0 0 1 0 0]]


In [13]:
for radius in [1, 3, 5, 7]:
    footprint = disk(radius)
    eroded = erosion(bin_img, footprint)
    plot_comparison(bin_img, eroded, f"Erosion (radius = {radius})")


Exercise 3

In [ ]:
from skimage.morphology import dilation, disk

# Try with a disk-shaped footprint of radius 2
footprint = disk(2)
dilated = dilation(bin_img, footprint)

plot_comparison(bin_img, dilated, 'Dilation (radius = 2)')


In [ ]:
for radius in [1, 3, 5, 7]:
    footprint = disk(radius)
    dilated = dilation(bin_img, footprint)
    plot_comparison(bin_img, dilated, f'Dilation (radius = {radius})')


Exercise 4

In [ ]:
from skimage.morphology import opening, disk

# Start with a small footprint (radius = 2)
footprint = disk(2)
opened = opening(bin_img, footprint)

plot_comparison(bin_img, opened, 'Opening (radius = 2)')


In [ ]:
for radius in [1, 3, 5, 7]:
    footprint = disk(radius)
    opened = opening(bin_img, footprint)
    plot_comparison(bin_img, opened, f'Opening (radius = {radius})')


Exercise 5

In [ ]:
from skimage.morphology import closing, disk

# Start with a disk-shaped footprint of radius 2
footprint = disk(2)
closed = closing(bin_img, footprint)

plot_comparison(bin_img, closed, 'Closing (radius = 2)')


In [ ]:
for radius in [1, 3, 5, 7]:
    footprint = disk(radius)
    closed = closing(bin_img, footprint)
    plot_comparison(bin_img, closed, f'Closing (radius = {radius})')


Exercise 6

In [ ]:
def compute_outline(bin_img):
    """
    Computes the outline of a binary image by XORing it with its dilation.
    The outline is where new pixels were added during dilation.
    """
    footprint = disk(1)
    dilated = dilation(bin_img, footprint)
    outline = np.logical_xor(dilated, bin_img)
    return outline

In [ ]:
lego_outline = compute_outline(bin_img)

# Visualize
import matplotlib.pyplot as plt

plt.figure(figsize=(5, 5))
plt.imshow(lego_outline, cmap='gray')
plt.title("Outline of LEGO Brick")
plt.axis("off")
plt.show()

Exercise 7

In [ ]:
from skimage.morphology import opening, closing, disk, dilation
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Opening with small disk (cleans up noise)
opened = opening(bin_img, footprint=disk(1))

# Step 2: Closing with large disk (fills holes and gaps)
closed = closing(opened, footprint=disk(15))

# Step 3: Compute outline
def compute_outline(bin_img):
    footprint = disk(1)
    dilated = dilation(bin_img, footprint)
    outline = np.logical_xor(dilated, bin_img)
    return outline

outline_img = compute_outline(closed)

# Step 4: Show the result
plt.figure(figsize=(6, 6))
plt.imshow(outline_img, cmap='gray')
plt.title("Outline after Opening (1) and Closing (15)")
plt.axis('off')
plt.show()


Exercise 8

In [ ]:
from skimage import io, color
from skimage.filters import threshold_otsu
from skimage.morphology import dilation, disk
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Load and convert to grayscale
im_org = io.imread("data/lego_7.png")
im_gray = color.rgb2gray(im_org)

# Step 2: Compute Otsu's threshold and binarize
T = threshold_otsu(im_gray)
bin_img = im_gray > T

# Step 3: Compute outline
def compute_outline(bin_img):
    footprint = disk(1)
    dilated = dilation(bin_img, footprint)
    outline = np.logical_xor(dilated, bin_img)
    return outline

outline = compute_outline(bin_img)

# Step 4: Show results
fig, ax = plt.subplots(1, 3, figsize=(15, 5))

ax[0].imshow(im_gray, cmap='gray')
ax[0].set_title("Original Grayscale Image")
ax[0].axis("off")

ax[1].imshow(bin_img, cmap='gray')
ax[1].set_title("Binary Image (Otsu Threshold)")
ax[1].axis("off")

ax[2].imshow(outline, cmap='gray')
ax[2].set_title("Outline of Objects")
ax[2].axis("off")

plt.tight_layout()
plt.show()


Exercise 9

In [ ]:
from skimage import io, color
from skimage.filters import threshold_otsu
from skimage.morphology import closing, dilation, disk
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Read and grayscale
im = io.imread("data/lego_7.png")
im_gray = color.rgb2gray(im)

# Step 2: Otsu's threshold
T = threshold_otsu(im_gray)
bin_img = im_gray > T

# Step 3: Try closing with different disk sizes
for radius in [1, 3, 5, 7, 11, 15]:
    closed = closing(bin_img, footprint=disk(radius))

    # Step 4: Compute outline
    def compute_outline(img):
        dil = dilation(img, footprint=disk(1))
        return np.logical_xor(dil, img)

    outline = compute_outline(closed)

    # Step 5: Show binary + outline
    fig, ax = plt.subplots(1, 2, figsize=(10, 5))
    ax[0].imshow(closed, cmap='gray')
    ax[0].set_title(f"Closed Binary (radius={radius})")
    ax[0].axis("off")

    ax[1].imshow(outline, cmap='gray')
    ax[1].set_title(f"Outline After Closing (radius={radius})")
    ax[1].axis("off")

    plt.tight_layout()
    plt.show()


Exercise 10

In [ ]:
from skimage import io, color
from skimage.filters import threshold_otsu
from skimage.morphology import closing, dilation, disk
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Load and convert to grayscale
im = io.imread("data/lego_3.png")
im_gray = color.rgb2gray(im)

# Step 2: Threshold using Otsu
T = threshold_otsu(im_gray)
bin_img = im_gray > T

# Step 3: Try multiple closing sizes
for radius in [3, 5, 7, 11]:
    closed = closing(bin_img, disk(radius))

    # Compute outline
    def compute_outline(img):
        dil = dilation(img, disk(1))
        return np.logical_xor(dil, img)

    outline = compute_outline(closed)

    # Step 4: Show binary and outline
    fig, ax = plt.subplots(1, 2, figsize=(10, 5))
    ax[0].imshow(closed, cmap='gray')
    ax[0].set_title(f"Closed Binary (radius={radius})")
    ax[0].axis("off")

    ax[1].imshow(outline, cmap='gray')
    ax[1].set_title(f"Outline After Closing (radius={radius})")
    ax[1].axis("off")

    plt.tight_layout()
    plt.show()


Exercise 11

In [ ]:
from skimage import io, color
from skimage.filters import threshold_otsu
from skimage.morphology import dilation, disk
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Load and convert to grayscale
im = io.imread("data/lego_9.png")
im_gray = color.rgb2gray(im)

# Step 2: Compute Otsu threshold and binarize
T = threshold_otsu(im_gray)
bin_img = im_gray > T

# Step 3: Compute outline function
def compute_outline(bin_img):
    dilated = dilation(bin_img, disk(1))
    return np.logical_xor(dilated, bin_img)

outline = compute_outline(bin_img)

# Step 4: Display original, binary, and outline
fig, axs = plt.subplots(1, 3, figsize=(15, 5))

axs[0].imshow(im_gray, cmap='gray')
axs[0].set_title("Grayscale Image")
axs[0].axis("off")

axs[1].imshow(bin_img, cmap='gray')
axs[1].set_title("Binary Image (Otsu)")
axs[1].axis("off")

axs[2].imshow(outline, cmap='gray')
axs[2].set_title("Outline of Binary Image")
axs[2].axis("off")

plt.tight_layout()
plt.show()


Exercise 12

In [ ]:
from skimage import io, color
from skimage.filters import threshold_otsu
from skimage.morphology import closing, dilation, disk
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Load and grayscale
img = io.imread("data/lego_9.png")
img_gray = color.rgb2gray(img)

# Step 2: Otsu thresholding
T = threshold_otsu(img_gray)
bin_img = img_gray > T

# Step 3: Apply closing with different radii
def compute_outline(bin_img):
    dilated = dilation(bin_img, disk(1))
    return np.logical_xor(dilated, bin_img)

for radius in [3, 5, 7, 9]:
    closed = closing(bin_img, disk(radius))
    outline = compute_outline(closed)

    # Display closed image and its outline
    fig, ax = plt.subplots(1, 2, figsize=(10, 5))
    ax[0].imshow(closed, cmap='gray')
    ax[0].set_title(f"Closed Binary (disk radius = {radius})")
    ax[0].axis("off")

    ax[1].imshow(outline, cmap='gray')
    ax[1].set_title("Outline After Closing")
    ax[1].axis("off")

    plt.tight_layout()
    plt.show()


Exercise 13

In [ ]:
from skimage import io, color
from skimage.filters import threshold_otsu
from skimage.morphology import closing, erosion, dilation, disk
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Load and grayscale
img = io.imread("data/lego_9.png")
img_gray = color.rgb2gray(img)

# Step 2: Threshold
T = threshold_otsu(img_gray)
bin_img = img_gray > T

# Step 3: Closing to fill internal holes (use a fixed radius)
closed = closing(bin_img, disk(5))

# Step 4: Try erosion with increasing sizes
def compute_outline(binary_img):
    dilated = dilation(binary_img, disk(1))
    return np.logical_xor(dilated, binary_img)

for radius in [3, 5, 7, 9, 11, 13]:
    eroded = erosion(closed, disk(radius))
    outline = compute_outline(eroded)

    fig, ax = plt.subplots(1, 2, figsize=(10, 5))
    ax[0].imshow(eroded, cmap='gray')
    ax[0].set_title(f"Eroded (disk radius = {radius})")
    ax[0].axis('off')

    ax[1].imshow(outline, cmap='gray')
    ax[1].set_title("Outline After Erosion")
    ax[1].axis('off')

    plt.tight_layout()
    plt.show()


Exercise 14

In [ ]:
from skimage.morphology import dilation, disk
import matplotlib.pyplot as plt

# Assume you already have:
# - bin_img: thresholded binary image
# - closed: result of closing (from Exercise 12)
# - eroded: result of erosion (from Exercise 13)
# Now dilate that eroded result

def compute_outline(img):
    dilated = dilation(img, disk(1))
    return np.logical_xor(dilated, img)

# Choose one erosion level (e.g. disk(11)) from Exercise 13
from skimage.morphology import erosion
eroded = erosion(closed, disk(11))  # You can adjust this

# Try dilating with increasing sizes
for radius in [3, 5, 7, 9, 11]:
    dilated = dilation(eroded, disk(radius))
    outline = compute_outline(dilated)

    fig, ax = plt.subplots(1, 2, figsize=(10, 5))
    ax[0].imshow(dilated, cmap='gray')
    ax[0].set_title(f"Dilated (disk radius = {radius})")
    ax[0].axis('off')

    ax[1].imshow(outline, cmap='gray')
    ax[1].set_title("Outline After Dilation")
    ax[1].axis('off')

    plt.tight_layout()
    plt.show()


Exercise 15

In [ ]:
from skimage import io, color
from skimage.filters import threshold_otsu
import matplotlib.pyplot as plt

# Step 1: Load and convert to grayscale
img = io.imread("data/puzzle_pieces.png")
gray = color.rgb2gray(img)

# Step 2: Threshold using Otsu's method
T = threshold_otsu(gray)
binary = gray > T

# Step 3: Display original and binary image
fig, ax = plt.subplots(1, 2, figsize=(12, 5))
ax[0].imshow(gray, cmap='gray')
ax[0].set_title("Grayscale Image")
ax[0].axis("off")

ax[1].imshow(binary, cmap='gray')
ax[1].set_title("Binary Image (Otsu)")
ax[1].axis("off")

plt.tight_layout()
plt.show()


Exercise 16

In [ ]:
from skimage.morphology import opening, dilation, disk
import numpy as np
import matplotlib.pyplot as plt

# Reuse the binary image from Exercise 15 (or reload and rethreshold as needed)
# For demonstration:
# binary = gray > threshold_otsu(gray)

# Step 1: Apply opening to clean binary image
cleaned = opening(binary, disk(7))  # Try 7, 9, or higher if needed

# Step 2: Compute outline
def compute_outline(bin_img):
    dilated = dilation(bin_img, disk(1))
    return np.logical_xor(dilated, bin_img)

outline = compute_outline(cleaned)

# Step 3: Display cleaned binary and outline
fig, ax = plt.subplots(1, 2, figsize=(12, 5))
ax[0].imshow(cleaned, cmap='gray')
ax[0].set_title("Cleaned Binary (Opening)")
ax[0].axis("off")

ax[1].imshow(outline, cmap='gray')
ax[1].set_title("Outline of Puzzle Pieces")
ax[1].axis("off")

plt.tight_layout()
plt.show()
